
__ERRITEM(buffer_empty,       "image buffer empty")
__ERRITEM(size_mismatch,      "image size mismatch")
__ERRITEM(pointer_size,       "image pointer size mismatch")
__ERRITEM(pointer_null,       "image pointer is null")
__ERRITEM(file_name_empty,    "image file name empty")
__ERRITEM(bad_index,          "image buffer bad index")
__ERRITEM(bad_size,           "image buffer bad size")
__ERRITEM(file_not_access,    "image file not access")
__ERRITEM(file_empty,         "image file empty")
__ERRITEM(format_not_support, "image format not support")
__ERRITEM(not_support,        "not support, use load_raw() function")
__ERRITEM(size_is_large,      "image rectangle size is large")
__ERRITEM(not_crop,           "not crop image rectangle")
__ERRITEM(not_support_type,   "image buffer not support type")
__ERRITEM(png_lib_error,      "png image error:")
__ERRITEM(jpg_lib_error,      "jpg library error")
    // BMP errors
__ERRITEM(bmp_not_format,     "image not bitmap format")
__ERRITEM(bmp_header_not_size,"bitmap image header not correct size")
__ERRITEM(bmp_color_not_24,   "bitmap image color not 24")
__ERRITEM(bmp_format_not_rgb, "bitmap image format not RGB (BGR)")
__ERRITEM(bmp_size_mismatch,  "bitmap image header size mismatch")
__ERRITEM(bmp_not_convertible,"bitmap image format not convertible")
__ERRITEM(bmp_incorrect_size, "bitmap image incorrect data size")

#undef __ERRITEM
